[package]
name = "shimui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-util = "0.3.21"
tokio = { version = "1.17.0", features = ["full"] }
warp = "0.3.2"
webbrowser = "0.6.0"
